#!/usr/bin/env python3
"""Build strategy-guide tables (Traditional Chinese Markdown) from the dump.

Reads build/data/*.tsv written by tools/dump_data.py and writes:

  docs/guide/tables.md      index + column legend
  docs/guide/scenarios.md   factions, bases, soldiers per scenario
  docs/guide/generals.md    400 characters: stats, affiliation, rankings
  docs/guide/bases.md       39 bases: static data, owners, domestic values
  docs/guide/treasures.md   treasures by kind with holders
  docs/guide/ranks.md       court ranks with mobilization and holders

    python3 tools/dump_data.py game/GENPEI build/data
    python3 tools/guide_tables.py [build/data [docs/guide]]

Fields that docs/formats.md §4 marks as guesses keep a （推測） mark in the
table headers. Column names and terms follow translation/glossary.tsv.
"""
from __future__ import annotations

import csv
import sys
import unicodedata
from collections import Counter, defaultdict
from pathlib import Path

GUESS = "（推測）"
HEADER = ("<!-- generated by tools/guide_tables.py from build/data/*.tsv; "
          "do not edit by hand -->\n\n")
NOTE = "> 由 `tools/guide_tables.py` 從 `build/data/*.tsv` 產生，請勿手改。\n"

# Japanese field / value -> UI term of the Chinese edition (glossary.tsv)
STATS = [("武力", "武力"), ("勇名", "威名"), ("弓術", "弓術"), ("知才", "智力"),
         ("優雅", "風雅"), ("忠節", "忠誠"), ("菩提", "菩提"), ("無常", "無常"),
         ("加護", "加護"), ("troop_quality", "兵質")]
GROWTH = ["武力", "勇名", "弓術", "知才", "優雅"]
RANKED = [s for s in STATS if s[0] != "忠節"]
SKILLS = [("music", "音樂"), ("waka", "和歌"), ("strategy", "奇略"),
          ("ships", "操船")]
KINDS = {"名馬": "名馬", "刀剣": "刀劍", "鎧": "鎧", "兜": "兜", "鞍": "鞍",
         "楽器": "樂器", "歌集": "歌集", "美術": "美術", "兵書": "兵書",
         "唐物": "唐物", "珍宝": "珍寶"}
# treasure bonus targets confirmed on 源義経's screen (formats.md §4.3)
KIND_EFFECT = {"刀剣": "武力、威名", "鎧": "威名", "兜": "威名", "兵書": "智力"}
CLAN_TYPES = {"源氏": "源氏", "平氏": "平氏", "藤原氏": "藤原氏", "豪族": "豪族"}
NON_GENERAL = 390
RENAMED = {"かむろ": "禿童"}  # kana-only name translated in main_data.tsv


def load(data: Path, name: str) -> list[dict]:
    with open(data / f"{name}.tsv", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f, delimiter="\t", quoting=csv.QUOTE_NONE,
                                   quotechar=None))


def ref(value: str) -> tuple[int, str] | None:
    """Parse an `id:name` reference; -1 means none."""
    if value in ("", "-1"):
        return None
    i, _, name = value.partition(":")
    return int(i), name.strip()


def refname(value: str, empty: str = "—") -> str:
    r = ref(value)
    return r[1] if r else empty


def per_scenario(rows: list[dict]) -> dict[int, dict[int, dict]]:
    out: dict[int, dict[int, dict]] = defaultdict(dict)
    for r in rows:
        out[int(r["scenario"])][int(r["id"])] = r
    return out


def table(head: list[str], rows: list[list]) -> str:
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines) + "\n"


def kana(s: str) -> str:
    return unicodedata.normalize("NFKC", s).strip()


def gname(r: dict) -> str:
    n = r["name"].strip()
    return RENAMED.get(n, n)


def num(v: str) -> str:
    return f"{int(v):,}"


def counted(names: list[str]) -> str:
    """'A、B×2' from a list of names, in first-seen order."""
    c = Counter(names)
    return "、".join(n if c[n] == 1 else f"{n}×{c[n]}" for n in dict.fromkeys(names))


def compact(values: list[str], years: list[int]) -> str:
    """One value if all scenarios agree, else 'yy:value／…' per change."""
    if len(set(values)) == 1:
        return values[0]
    out, last = [], None
    for y, v in zip(years, values):
        if v != last:
            out.append(f"{y % 100}:{v}")
            last = v
    return "／".join(out)


class Guide:
    def __init__(self, data: Path):
        self.scen = load(data, "scenarios")
        self.years = [int(r["year"]) for r in self.scen]
        self.gen = per_scenario(load(data, "generals"))
        self.clans = per_scenario(load(data, "clans"))
        self.places = per_scenario(load(data, "places"))
        self.ranks = per_scenario(load(data, "ranks"))
        self.treasures = per_scenario(load(data, "treasures"))
        self.regions = per_scenario(load(data, "regions"))
        self.n = len(self.years)
        self.counts: dict = {}

    # -- shared helpers --------------------------------------------------

    def clan_name(self, s: int, value: str, empty: str = "無主") -> str:
        r = ref(value)
        if r is None:
            return empty
        return refname(self.clans[s][r[0]]["leader"], empty)

    def affiliation(self, s: int, g: dict) -> str:
        st = g["status"]
        if st == "死亡":
            return "未登場" if s == 0 else "—"
        if st == "在野":
            return "在野"
        if st == "棟梁":
            return "**棟梁**"
        leader = self.clan_name(s, g["clan"], "無")
        if st == "御家人":
            return leader
        if st.startswith("落武者"):
            return f"{leader}・身分6{GUESS}"
        return f"{leader}・{st}"

    def treasure_of(self, s: int, gid: int) -> list[dict]:
        return [t for t in self.treasures[s].values()
                if (r := ref(t["owner"])) and r[0] == gid]

    # -- pages -----------------------------------------------------------

    def scenarios(self) -> str:
        out = [HEADER, "# 劇本總覽\n\n", NOTE, "\n",
               "四個劇本的登場勢力、據點與兵力。數字是劇本初始值（`Sndata.gp`），"
               "開局後遊戲會再調整（例如動員力改為官位值）。"
               "財貨、兵糧欄位的意義屬推測。\n"]
        for s, sc in enumerate(self.scen):
            places = self.places[s]
            gens = self.gen[s]
            clan_ids = [ref(c)[0] for c in sc["clans"].split(",")]
            big4 = [self.clan_name(s, f"{i}:", "—") for i in range(4)]
            gov = [refname(self.clans[s][i]["leader"])
                   for i in clan_ids if self.clans[s][i]["government"] == "1"]
            out.append(f"\n## {sc['year']} 年 {sc['month']} 月\n\n")
            out.append(f"登場勢力 {len(clan_ids)} 個；掌握政權（佔有平安京）："
                       f"{'、'.join(gov) or '—'}。\n\n")
            rows, holdings = [], []
            for cid in clan_ids:
                c = self.clans[s][cid]
                own = [p for p in places.values()
                       if (r := ref(p["clan"])) and r[0] == cid]
                members = [g for g in gens.values()
                           if (r := ref(g["clan"])) and r[0] == cid
                           and g["status"] != "死亡"]
                if len(own) != int(c["n_places"]) or len(members) != int(c["n_generals"]):
                    print(f"warning: {sc['year']} clan {cid}: counts "
                          f"{len(own)}/{len(members)} vs record "
                          f"{c['n_places']}/{c['n_generals']}", file=sys.stderr)
                leader = refname(c["leader"])
                rels = [c[f"rel_c{i}"] for i in range(4) if big4[i] != "—"]
                rows.append([
                    leader, CLAN_TYPES.get(c["type"], c["type"]), len(own),
                    len(members), num(str(sum(int(p["soldiers"]) for p in own))),
                    num(str(sum(int(p["gold"]) for p in own))),
                    num(str(sum(int(p["food"]) for p in own))),
                    "○" if c["government"] == "1" else "", c["court?"], *rels])
                holdings.append(f"- **{leader}**（{len(own)}）："
                                + "、".join(p["name"] for p in own))
            ronin = sum(g["status"] == "在野" for g in gens.values())
            dead = sum(g["status"] == "死亡" for i, g in gens.items() if i < NON_GENERAL)
            head = ["勢力（棟梁）", "類別", "據點", "武將", "雜兵", f"財貨{GUESS}",
                    f"兵糧{GUESS}", "政權", f"朝廷{GUESS}"]
            head += [f"對{b}友好" for b in big4 if b != "—"]
            out.append(table(head, rows))
            out.append(f"\n在野武將 {ronin} 人；"
                       f"{'未登場' if s == 0 else '已死亡或未登場'} {dead} 人"
                       f"（不含 390–399 非武將角色）。\n\n")
            out.append("**各勢力據點**\n\n" + "\n".join(holdings) + "\n")
        return "".join(out)

    def generals(self) -> str:
        y = self.years
        ids = sorted(self.gen[0])
        first = {}
        for i in ids:
            alive = [s for s in range(self.n) if self.gen[s][i]["status"] != "死亡"]
            first[i] = alive[0] if alive else 0
        out = [HEADER, "# 武將一覽\n\n", NOTE, "\n",
               "共 400 筆：0–389 是武將，390–399 是劇情用的非武將角色（文末另列）。"
               "名字保留日文漢字原樣；讀音由遊戲內半形假名轉成全形。\n\n",
               "- 能力值是**登場的第一個劇本**的原始值（0–389 全員在 1180 年就已登場，"
               "所以就是 1180 年值），**不含寶物加成**；畫面上的數字＝原始值＋寶物加成"
               "（例：源義経 1185 年武力 94＋今剣 8＝102）。\n"
               "- 約百名武將的武力、威名、弓術、智力、風雅會隨劇本成長或衰退，"
               "姓名後標 † 者見〈[能力隨劇本變化](#能力隨劇本變化)〉。\n"
               "- 忠誠是 1180 年值，棟梁顯示 —，在野為 0；各劇本差異大，不另列。\n"
               "- 體力在劇本中全員 100，不列。\n"
               "- 動員力：有官位者為官位的動員力（開局後遊戲以此為準），"
               "無官位者為劇本 record 值。\n\n"]

        # 1. stats
        out.append("## 能力\n\n")
        rows = []
        for i in ids[:NON_GENERAL]:
            g = self.gen[first[i]][i]
            grow = any(len({self.gen[s][i][k] for s in range(self.n)}) > 1
                       for k in GROWTH)
            stats = []
            for k, _ in STATS:
                v = g[k]
                if k == "忠節" and g["status"] == "棟梁":
                    v = "—"
                stats.append(v)
            rk = ref(g["rank"])
            mob = (self.ranks[first[i]][rk[0]]["mobilize"] if rk else g["mobilize"])
            rows.append([i, gname(g) + (" †" if grow else ""), *stats, num(mob),
                         *(g[k] for k, _ in SKILLS)])
        out.append(table(["#", "姓名", *(c for _, c in STATS), "動員力",
                          *(c for _, c in SKILLS)], rows))

        # 2. affiliation per scenario
        out.append("\n## 所屬、官位與生平\n\n"
                   "所屬欄：勢力以棟梁名稱呼；只寫棟梁名＝御家人，"
                   "「・代官」＝該勢力的據點代官，**棟梁**＝自己就是勢力之主，"
                   "「身分6（推測）」只出現兩次（1183 瀬尾兼康、1184 平重衡，"
                   "史實上都是被俘，可能是捕虜而非落武者）。"
                   "官位若各劇本不同，寫成「年:官位」依序列出（— 為無）。"
                   "父親依血緣碼推得（formats.md §4.3）。\n\n")
        rows = []
        for i in ids[:NON_GENERAL]:
            g0 = self.gen[0][i]
            ranks = [refname(self.gen[s][i]["rank"]) for s in range(self.n)]
            rows.append([i, gname(g0),
                         f"{kana(g0['surname_kana'])} {kana(g0['given_kana'])}",
                         g0["born"], refname(g0["parent"]),
                         refname(g0["home?"]),
                         *(self.affiliation(s, self.gen[s][i]) for s in range(self.n)),
                         compact(ranks, y)])
        out.append(table(["#", "姓名", "讀音", "生年", "父", f"本據{GUESS}",
                          *(f"{yr}" for yr in y), "官位"], rows))

        # 3. growth
        out.append("\n## 能力隨劇本變化\n\n"
                   "只列武力、威名、弓術、智力、風雅有變化的武將，"
                   "每格依序為「武力／威名／弓術／智力／風雅」；— 為已死亡。\n\n")
        rows = []
        for i in ids[:NON_GENERAL]:
            if not any(len({self.gen[s][i][k] for s in range(self.n)}) > 1
                       for k in GROWTH):
                continue
            cells = []
            for s in range(self.n):
                g = self.gen[s][i]
                cells.append("—" if g["status"] == "死亡"
                             else "／".join(g[k] for k in GROWTH))
            rows.append([i, gname(self.gen[0][i]), *cells])
        out.append(table(["#", "姓名", *(str(yr) for yr in y)], rows))
        grow_n = len(rows)

        # 4. rankings
        out.append(f"\n## 能力排行（{y[0]} 年，前 20 名）\n\n"
                   f"{y[0]} 年劇本的原始值（不含寶物），不含 390–399。"
                   "同分同名次，第 20 名同分者全列。"
                   "成長型武將到後期劇本會更高，見上表。\n")
        for k, label in RANKED:
            pool = sorted(((int(self.gen[0][i][k]), i) for i in ids[:NON_GENERAL]),
                          key=lambda t: (-t[0], t[1]))
            rows, rank = [], 0
            for pos, (v, i) in enumerate(pool):
                if pos == 0 or v != pool[pos - 1][0]:
                    rank = pos + 1
                if rank > 20:
                    break
                g = self.gen[0][i]
                rows.append([rank, gname(g), v, self.affiliation(0, g)])
            out.append(f"\n### {label}\n\n")
            out.append(table(["名次", "武將", label, f"{y[0]} 所屬"], rows))

        # 5. skill holders
        out.append("\n## 特技持有者\n\n")
        for k, label in SKILLS:
            who = [gname(self.gen[0][i]) for i in ids[:NON_GENERAL]
                   if self.gen[0][i][k] == "○"]
            out.append(f"- **{label}**（{len(who)} 人）：{'、'.join(who)}\n")

        # 6. non-generals
        out.append("\n## 非武將角色（390–399）\n\n"
                   "劇情事件用的角色，身分在劇本中都是「死亡／未登場」、無勢力。"
                   "「かむろ」中文版譯為「禿童」。\n\n")
        out.append(table(["#", "名稱"],
                         [[i, gname(self.gen[0][i])] for i in ids[NON_GENERAL:]]))
        self.counts["generals"] = (len(ids[:NON_GENERAL]), grow_n)
        return "".join(out)

    def bases(self) -> str:
        y = self.years
        p0 = self.places[0]
        out = [HEADER, "# 據點一覽\n\n", NOTE, "\n",
               "39 個據點。人口、雜兵、雜兵質已在實機畫面確認；"
               "商業値、治安、農業値、財貨、兵糧是依數值量級對應畫面欄位，"
               "標（推測）。人口上限、農業上限是四個劇本都不變的欄位，意義屬推測。"
               "合戰地圖是據點在戰略地圖節點上記的地圖編號（Hchikei.gp），"
               "鎌倉 30、平泉 31、福原 32、屋島 33 專用，其餘共用 34–36（推測，證據強）。\n\n"
               "注意：劇本值不等於存檔值。例如平安京人口在 1185 年劇本是 "
               f"{num(self.places[3][17]['population'])}，"
               "1185 年 10 月存檔畫面則是 41,600（開局後每季會變動）。\n\n"]

        out.append("## 基本資料\n\n")
        rows = []
        for i, p in sorted(p0.items()):
            rows.append([i, p["name"], kana(p["kana"]), refname(p["region"]),
                         p["adjacent"].replace(",", "、"), num(p["pop_max?"]),
                         p["farm_max?"], p["battle_map?"]])
        out.append(table(["#", "據點", "讀音", "地方", "鄰接據點",
                          f"人口上限{GUESS}", f"農業上限{GUESS}",
                          f"合戰地圖{GUESS}"], rows))

        out.append("\n## 各劇本歸屬\n\n格式為「勢力棟梁（代官）」；"
                   "代官就是棟梁本人時只寫一次。\n\n")
        rows = []
        for i in sorted(p0):
            cells = []
            for s in range(self.n):
                p = self.places[s][i]
                owner = self.clan_name(s, p["clan"])
                gov = refname(p["governor"], "")
                cells.append(owner if gov in ("", owner) else f"{owner}（{gov}）")
            rows.append([i, p0[i]["name"], *cells])
        out.append(table(["#", "據點", *(str(yr) for yr in y)], rows))

        for s, yr in enumerate(y):
            out.append(f"\n## {yr} 年劇本的內政數值\n\n")
            rows = []
            for i, p in sorted(self.places[s].items()):
                rows.append([i, p["name"], self.clan_name(s, p["clan"]),
                             num(p["population"]), p["commerce"], p["security"],
                             p["farm"], num(p["gold"]), num(p["food"]),
                             num(p["soldiers"]), p["soldier_quality"],
                             p["n_members"], p["n_ronin"]])
            out.append(table(["#", "據點", "勢力", "人口", f"商業値{GUESS}",
                              f"治安{GUESS}", f"農業値{GUESS}", f"財貨{GUESS}",
                              f"兵糧{GUESS}", "雜兵", "雜兵質", "武將", "在野"],
                             rows))
        return "".join(out)

    def treasures_page(self) -> str:
        y = self.years
        t0 = self.treasures[0]
        out = [HEADER, "# 寶物（名物）一覽\n\n", NOTE, "\n",
               f"共 {len(t0)} 件（同名寶物每件一筆，例如砂金 15 件），"
               "以下把同名同效果值的合併成一列、標件數。"
               "持有人欄列出各劇本開局時的持有武將，×n 為件數；"
               "「無主 n」是劇本中沒有武將持有的件數（可能由商人出售或事件取得，未確認）。\n\n"
               "**效果**：效果值已在實機確認。加成對象只在源義経的畫面驗證過："
               "刀劍加武力與威名、鎧與兜加威名、兵書加智力；"
               "**同一種類只取效果最高的一件**（推測）。其餘種類的加成對象未詳。\n\n"]
        groups: dict[tuple, list[int]] = defaultdict(list)
        for i, t in sorted(t0.items()):
            groups[(t["kind"], t["name"], int(t["value"]))].append(i)
        summary = []
        for kind_ja, kind in KINDS.items():
            keys = sorted((k for k in groups if k[0] == kind_ja),
                          key=lambda k: (-k[2], groups[k][0]))
            items = sum(len(groups[k]) for k in keys)
            summary.append([kind, items, len(keys),
                            KIND_EFFECT.get(kind_ja, "未詳") + (
                                GUESS if kind_ja in KIND_EFFECT else "")])
            out.append(f"\n## {kind}\n\n加成對象："
                       f"{KIND_EFFECT.get(kind_ja, '未詳')}"
                       f"{GUESS if kind_ja in KIND_EFFECT else ''}\n\n")
            rows = []
            for k in keys:
                cells = []
                for s in range(self.n):
                    owners = [refname(self.treasures[s][i]["owner"], "")
                              for i in groups[k]]
                    held = [o for o in owners if o]
                    free = len(owners) - len(held)
                    cell = counted(held)
                    if free:
                        cell += ("；" if cell else "") + (
                            f"無主 {free}" if len(owners) > 1 else "無主")
                    cells.append(cell)
                rows.append([k[1], k[2], len(groups[k]), *cells])
            out.append(table(["名稱", "效果值", "件數", *(str(yr) for yr in y)],
                             rows))
        out.insert(5, "## 種類總覽\n\n" + table(
            ["種類", "件數", "品項", "加成對象"], summary))
        return "".join(out)

    def ranks_page(self) -> str:
        y = self.years
        r0 = self.ranks[0]
        out = [HEADER, "# 官位一覽\n\n", NOTE, "\n",
               f"共 {len(r0)} 個名額；同名官位有多筆＝可同時任命多人，"
               "以下合併成一列。官位名保留日文原樣。\n\n"
               "- **動員力**：武將任官後動員力改為此值（實機：源義経任伊予守 → 2,200）。\n"
               "- **武／文**：record 裡兩個效果值，近衛、兵衛等武官前者較大，"
               "大臣、卿後者較大，所以推測為武官／文官的權重，實際作用未確認。\n"
               "- 任官者欄是各劇本開局時的任官者，— 為空缺。\n\n"]
        groups: dict[str, list[int]] = defaultdict(list)
        for i, r in sorted(r0.items()):
            groups[r["name"]].append(i)
        order = sorted(groups, key=lambda n: (-int(r0[groups[n][0]]["mobilize"]),
                                              groups[n][0]))
        rows = []
        for name in order:
            first = r0[groups[name][0]]
            cells = []
            for s in range(self.n):
                held = [refname(self.ranks[s][i]["holder"], "") for i in groups[name]]
                cells.append("、".join(h for h in held if h) or "—")
            rows.append([name, len(groups[name]), num(first["mobilize"]),
                         first["military?"], first["court?"], *cells])
        out.append(table(["官位", "名額", "動員力", f"武{GUESS}", f"文{GUESS}",
                          *(str(yr) for yr in y)], rows))
        self.counts["ranks"] = len(rows)
        return "".join(out)

    def index(self) -> str:
        y = self.years
        return "".join([HEADER, "# 攻略用資料表\n\n", NOTE, "\n",
            f"從遊戲的劇本資料（`Sndata.gp`，{'、'.join(map(str, y))} 年四個劇本）"
            "整理出的資料表。欄位格式與可信度見 `docs/formats.md` §4；"
            "標（推測）的欄位是依數值量級或相關性推定，尚未在實機畫面逐一確認。\n\n",
            "## 目錄\n\n",
            "- [劇本總覽](scenarios.md)：各劇本的勢力、棟梁、據點數、武將數、兵力\n",
            "- [武將一覽](generals.md)：400 人的能力、特技、所屬、官位、能力排行\n",
            "- [據點一覽](bases.md)：39 個據點的地方、鄰接、內政數值、各劇本歸屬\n",
            "- [寶物一覽](treasures.md)：名物依種類分列，效果值與持有人\n",
            "- [官位一覽](ranks.md)：官位的動員力與任官者\n",
            "\n## 欄位說明\n\n",
            "中文用語依中文版畫面（`translation/glossary.tsv`），括號內是日文原文。\n\n",
            "### 武將\n\n",
            table(["欄位", "說明"], [
                ["武力（武力）", "個人武勇。刀劍類寶物加成"],
                ["威名（勇名）", "武名聲望。刀劍、鎧、兜類寶物加成"],
                ["弓術（弓術）", "弓箭技術"],
                ["智力（知才）", "智謀。兵書類寶物加成"],
                ["風雅（優雅）", "風雅之心（畫面說明「風雅の心を愉しむ」）"],
                ["忠誠（忠節）", "對主君的忠誠；棟梁顯示 —，在野、死亡為 0"],
                ["菩提（菩提）", "信佛之心；僧侶偏高"],
                ["無常（無常）", "無常觀"],
                ["加護（加護）", "神佛庇佑（「神仏の加護を頼む」）"],
                ["體力（体力）", "劇本中全員 100，合戰後會下降"],
                ["兵質（兵質）", "所率動員兵的素質"],
                ["動員力（動員力）", "可動員的兵數；任官後改為官位的動員力"],
                ["音樂、和歌、奇略、操船（音楽、和歌、奇略、操船）", "特技，○ 有 × 無"],
                ["身分（身分）", "棟梁、代官、御家人、在野；另有落武者、俘虜（捕虜）等"],
                ["官位（官位）", "朝廷官職，決定動員力"],
                ["本據（推測）", "各劇本都不變的據點編號，疑為出身地"],
            ]),
            "\n能力值都不含寶物加成；畫面數值＝原始值＋寶物加成"
            "（同種類只取最高一件，推測）。\n\n### 據點\n\n",
            table(["欄位", "說明", "可信度"], [
                ["人口（人口）", "據點人口", "實機確認"],
                ["人口上限", "各劇本不變", "推測"],
                ["商業値（商業値）", "商業開發程度", "推測"],
                ["治安（治安）", "治安度", "推測"],
                ["農業値（農業値）", "農業開發程度", "推測"],
                ["農業上限", "各劇本不變", "推測"],
                ["財貨（財貨）", "金錢存量", "推測"],
                ["兵糧（兵糧）", "糧食存量", "推測"],
                ["雜兵（雑兵）", "據點駐守的雜兵數", "實機確認"],
                ["雜兵質（雑兵質）", "雜兵素質", "實機確認"],
                ["合戰地圖", "在該據點開戰時用的合戰地圖編號", "推測（強）"],
            ]),
            "\n### 勢力\n\n",
            table(["欄位", "說明", "可信度"], [
                ["類別（種別）", "源氏、平氏、藤原氏、豪族", "確定"],
                ["友好（友好）", "對頼朝、平家、義仲、奧州藤原四大勢力的友好度", "確定"],
                ["朝廷（朝廷）", "與朝廷的關係值（5–50）", "推測"],
                ["政權（政権）", "佔有平安京的勢力", "確定"],
            ]),
            "\n### 寶物、官位\n\n",
            table(["欄位", "說明", "可信度"], [
                ["種類", "名馬、刀劍、鎧、兜、鞍、樂器、歌集、美術、兵書、唐物、珍寶", "確定"],
                ["效果值", "寶物的加成值", "實機確認"],
                ["動員力", "官位的動員力", "實機確認"],
                ["武／文", "官位的兩個效果值", "推測"],
            ]),
            "\n## 重新產生\n\n```bash\n"
            "python3 tools/dump_data.py game/GENPEI build/data\n"
            "python3 tools/guide_tables.py\n```\n"])


def main() -> None:
    data = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("build/data")
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("docs/guide")
    out.mkdir(parents=True, exist_ok=True)
    g = Guide(data)
    pages = {"scenarios.md": g.scenarios(), "generals.md": g.generals(),
             "bases.md": g.bases(), "treasures.md": g.treasures_page(),
             "ranks.md": g.ranks_page(), "tables.md": g.index()}
    for name, text in pages.items():
        (out / name).write_text(text, encoding="utf-8")
        print(f"{out / name}: {text.count(chr(10))} lines")


if __name__ == "__main__":
    main()
